include_guard(GLOBAL)
if(NOT CMAKE_SCRIPT_MODE_FILE)
    include(FetchContent)
    include(ExternalProject)
endif()

function(dd_dependency_arguments manifest name output)
    file(READ "${manifest}" declarations)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
    string(JSON url GET "${declarations}" dependencies "${name}" url)
    string(JSON digest ERROR_VARIABLE missing_hash GET "${declarations}" dependencies "${name}" sha256)
    if(NOT missing_hash)
        string(LENGTH "${digest}" size)
        if(NOT size EQUAL 64 OR NOT digest MATCHES "^[0-9a-f]+$" OR NOT url MATCHES "^https://")
            message(FATAL_ERROR "Archive ${name} requires HTTPS and SHA-256")
        endif()
        set(arguments URL "${url}" URL_HASH "SHA256=${digest}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE TLS_VERIFY TRUE)
    else()
        string(JSON commit GET "${declarations}" dependencies "${name}" commit)
        string(LENGTH "${commit}" size)
        if(NOT size EQUAL 40 OR NOT commit MATCHES "^[0-9a-f]+$")
            message(FATAL_ERROR "Git dependency ${name} requires a full commit")
        endif()
        set(arguments GIT_REPOSITORY "${url}" GIT_TAG "${commit}" GIT_SHALLOW FALSE
            GIT_SUBMODULES "" GIT_SUBMODULES_RECURSE FALSE
            GIT_CONFIG protocol.ext.allow=never protocol.file.allow=never core.hooksPath=/dev/null)
    endif()
    if(url MATCHES "[;\"$\\ \t\r\n]")
        message(FATAL_ERROR "Invalid acquisition URL")
    endif()
    set(${output} "${arguments}" PARENT_SCOPE)
endfunction()

function(dd_check_archive_source source initialize)
    if(IS_SYMLINK "${source}" OR IS_SYMLINK "${source}.dd-sha256")
        message(FATAL_ERROR "Refusing linked archive source or fingerprint")
    endif()
    file(GLOB_RECURSE paths RELATIVE "${source}" LIST_DIRECTORIES FALSE "${source}/*")
    list(SORT paths)
    set(fingerprint "")
    foreach(path IN LISTS paths)
        if(IS_SYMLINK "${source}/${path}")
            message(FATAL_ERROR "Linked archive content is not supported")
        endif()
        file(SHA256 "${source}/${path}" digest)
        string(APPEND fingerprint "${path}:${digest}\n")
    endforeach()
    string(SHA256 digest "${fingerprint}")
    if(EXISTS "${source}.dd-sha256")
        file(READ "${source}.dd-sha256" previous)
        if(NOT previous STREQUAL digest)
            message(FATAL_ERROR "Preserving edited archive source: ${source}")
        endif()
    elseif(initialize)
        file(WRITE "${source}.dd-sha256" "${digest}")
    elseif(EXISTS "${source}")
        message(FATAL_ERROR "Unverified archive source: ${source}. Inspect it manually.")
    endif()
endfunction()

function(dd_check_dependency_source source commit)
    if(IS_SYMLINK "${source}")
        message(FATAL_ERROR "Refusing linked dependency source: ${source}")
    endif()
    if(EXISTS "${source}")
        if(NOT EXISTS "${source}/.git")
            message(FATAL_ERROR "Occupied dependency source: ${source}. Inspect it manually.")
        endif()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source}" status --porcelain --untracked-files=all
            RESULT_VARIABLE status_result OUTPUT_VARIABLE changes ERROR_VARIABLE status_error)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source}" rev-parse HEAD
            RESULT_VARIABLE head_result OUTPUT_VARIABLE head OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(NOT status_result EQUAL 0 OR NOT head_result EQUAL 0 OR NOT changes STREQUAL "" OR NOT head STREQUAL commit)
            message(FATAL_ERROR "Preserving modified or mismatched dependency: ${source}. Inspect it manually before configuring.")
        endif()
    endif()
endfunction()

function(dd_load_dependencies manifest)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
    file(READ "${manifest}" declarations)
    string(JSON schema GET "${declarations}" schema)
    if(NOT schema EQUAL 1)
        message(FATAL_ERROR "Unsupported dd dependency schema")
    endif()
    string(JSON count LENGTH "${declarations}" dependencies)
    if(count EQUAL 0)
        return()
    endif()
    find_package(Git REQUIRED)
    set(ENV{GIT_TERMINAL_PROMPT} 0)
    set(ENV{GCM_INTERACTIVE} Never)
    set(ENV{GIT_SSH_COMMAND} "ssh -oBatchMode=yes")
    set(FETCHCONTENT_TRY_FIND_PACKAGE_MODE NEVER)
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
        string(JSON name MEMBER "${declarations}" dependencies ${index})
        string(JSON url GET "${declarations}" dependencies "${name}" url)
        string(JSON archive_hash ERROR_VARIABLE not_archive GET "${declarations}" dependencies "${name}" sha256)
        if(NOT not_archive)
            set(commit "${archive_hash}")
        else()
            string(JSON commit GET "${declarations}" dependencies "${name}" commit)
        endif()
        string(JSON method GET "${declarations}" dependencies "${name}" method)
        string(LENGTH "${commit}" commit_length)
        if(NOT name MATCHES "^[a-z][a-z0-9-]*$" OR NOT commit MATCHES "^[0-9a-f]+$" OR (NOT commit_length EQUAL 40 AND NOT commit_length EQUAL 64))
            message(FATAL_ERROR "Dependency names and full commit IDs must be valid: ${name}")
        endif()
        if(NOT url MATCHES "^(https|ssh)://[^/]+/.+" OR url MATCHES "[;\"$\\ \t\r\n]")
            message(FATAL_ERROR "Invalid Git URL for ${name}")
        endif()
        dd_dependency_arguments("${manifest}" "${name}" acquisition)
        if(method STREQUAL "application")
            continue()
        endif()
        if(NOT method STREQUAL "fetchcontent" AND NOT method STREQUAL "externalproject")
            message(FATAL_ERROR "Unsupported dependency method: ${method}")
        endif()
        string(REPLACE "-" "_" content_name "${name}")
        string(TOUPPER "${content_name}" upper_name)
        if(DEFINED FETCHCONTENT_SOURCE_DIR_${upper_name} AND NOT "${FETCHCONTENT_SOURCE_DIR_${upper_name}}" STREQUAL "")
            message(FATAL_ERROR "Source overrides bypass recorded pins: ${name}. Use a separate development integration explicitly.")
        endif()
        set(cache "${CMAKE_BINARY_DIR}/_deps")
        if(IS_SYMLINK "${cache}")
            message(FATAL_ERROR "Refusing linked dependency cache: ${cache}")
        endif()
        set(source "${cache}/${name}-${commit}-src")
        string(SUBSTRING "${commit}" 0 16 short_commit)
        set(binary "${cache}/${name}-${short_commit}-build")
        set(install "${cache}/${name}-${short_commit}-install")
        set(prefix "${cache}/${name}-${short_commit}-external")
        foreach(directory IN ITEMS "${binary}" "${install}" "${prefix}")
            if(IS_SYMLINK "${directory}" OR IS_SYMLINK "${directory}/.dd-commit")
                message(FATAL_ERROR "Refusing linked dependency directory: ${directory}")
            endif()
            if(EXISTS "${directory}/.dd-commit")
                file(READ "${directory}/.dd-commit" recorded_commit)
                if(NOT recorded_commit STREQUAL commit)
                    message(FATAL_ERROR "Dependency cache prefix collision: ${directory}")
                endif()
            endif()
            file(MAKE_DIRECTORY "${directory}")
            file(WRITE "${directory}/.dd-commit" "${commit}")
        endforeach()
        if(not_archive)
            dd_check_dependency_source("${source}" "${commit}")
        else()
            dd_check_archive_source("${source}" FALSE)
        endif()
        if(method STREQUAL "fetchcontent")
            FetchContent_Declare(${content_name}
                ${acquisition}
                SOURCE_DIR "${source}" BINARY_DIR "${binary}" UPDATE_COMMAND "")
            FetchContent_MakeAvailable(${content_name})
            if(not_archive)
                dd_check_dependency_source("${source}" "${commit}")
            else()
                dd_check_archive_source("${source}" TRUE)
            endif()
        else()
            ExternalProject_Add(dd-dep-${name}
                ${acquisition}
                PREFIX "${prefix}"
                SOURCE_DIR "${source}" BINARY_DIR "${binary}" INSTALL_DIR "${install}"
                UPDATE_COMMAND ""
                CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>"
                    "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
                    "-DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}"
                    "-DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}"
                    "-DCMAKE_CXX_STANDARD:STRING=20"
                    "-DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=${CMAKE_MSVC_RUNTIME_LIBRARY}")
            if(NOT not_archive)
                ExternalProject_Add_Step(dd-dep-${name} verify-source
                    COMMAND "${CMAKE_COMMAND}" "-DDD_ARCHIVE_SOURCE=${source}" -DDD_ARCHIVE_INITIALIZE=ON -P "${CMAKE_CURRENT_FUNCTION_LIST_FILE}"
                    DEPENDEES download DEPENDERS configure ALWAYS TRUE)
            endif()
        endif()
        set(${content_name}_SOURCE_DIR "${source}" PARENT_SCOPE)
        set(${content_name}_BINARY_DIR "${binary}" PARENT_SCOPE)
        set(${content_name}_INSTALL_DIR "${install}" PARENT_SCOPE)
    endforeach()
endfunction()

if(CMAKE_SCRIPT_MODE_FILE AND DEFINED DD_ARCHIVE_SOURCE)
    dd_check_archive_source("${DD_ARCHIVE_SOURCE}" "${DD_ARCHIVE_INITIALIZE}")
endif()